name: (API) Deploy API

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checking out Repository
        uses: actions/checkout@v4

      - name: Setting up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.3.0'

      - name: Setting up bun
        uses: oven-sh/setup-bun@v2

      - name: Installing dependencies
        run: bun install
        working-directory: api

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: api
          command: deploy --env production
