name: (CI) Automatic Build

on:
  workflow_dispatch: {}
  schedule:
  - cron: '*/10 * * * *'

jobs:
  build:
    name: Automatic Build
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
      NODE_ENV: production

    steps:
    - name: Checking out Repository
      uses: actions/checkout@v4

    - name: Setting up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Setting up node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.3.0'

    - name: Setting up bun
      uses: oven-sh/setup-bun@v2

    - name: Installing dependencies
      run: bun install
      working-directory: ci

    - name: Run automatic build
      run: bun run start
      working-directory: ci
